### ISSUE TITLE
Resharper 9 support

### ISSUE THREAD

**Issue by forgetaboutit** [ThatShawGuy/VBSharper#3]
As Jetbrains recently released Resharper 9, I'd really love to see support for it!

**Comment by mr-unowen** [comment]
I would love to see the support for v9 also, as soon as possible ;) .
Btw. I have even downgraded back to v8 the moment I realized VBSharper is not in the new extension gallery.
How far are you right now?

**Comment by ThatShawGuy** [comment]
Sorry for the delay. I took a stab at the upgrade recently and it is taking longer than I hoped. In opening up extensions to all of their products they took a step back in their support for those of us who were developing extensions specifically for R#. I'll be spending some more time on it this evening.

**Comment by ThatShawGuy** [comment]
VBSharper for R# 9 is now live.
